# .bashrc

# User specific aliases and functions

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# set -o vi

#if [ ! -r .ssh/authorized_keys ] ; then
#	ssh-keygen -t rsa
#	cp .ssh/id_rsa.pub .ssh/authorized_keys
#fi

#PS1="\e[0;34m$PS1\e[m"

# modules definitions
#if [ -n "$MODULESHOME" ] ; then
#	module use /shr/modules
#	module load matlab/default
#	module load intel/cce/10.1/default
#	module load gcc/4.4/default
#	module load ncbi/default
#	module load blat/default
#fi

module load gcc-4.4
module load java-1.6_18
module load fftw-3.2.2
#module load python-2.7.3
#module load R-2.12.2
module load samtools-0.1.18 
module load tophat-1.4.1
module load bowtie-0.12.7
module load bamtools_5.31.2012
module load gnuplot-4.4.3
module load casava-1.8.2
#module load bwa-0.5.9
#module load cufflinks-1.3.0
#module load blast
#module load picardtools-1.58
module load picard-tools-1.75
module load matlab-2011b
module load emacs-24.1
#module load vcftools_0.1.9
#module load gatk-2.0.39
module load gatk-2.2-4
module load R-2.15.2
module load IGV-2.0.34
#module load bedtools
#export LAMRSH="ssh -x"
module load boost-1.38.0
module load zlib-1.2.7
#module load python-3.2.3
module load tabix
module load jdk-7.7
module load matlab/2014a
module load vim/default
# module load gcc/default
module load gsl-1.15

module load lapack-blas-libs
module load R/3.0.2
# module load R/3.1.0

# Custom modules
module use /apps/modulefiles/lab
module load miket/git/2.0.1
module load miket/bwa/0.7.10
module load miket/freebayes/0.9.14
module load miket/lumpy/0.2.5
module load miket/parallel/20140622
module load miket/sambamba/0.4.7
module load miket/samblaster/0.1.16
module load miket/snpEff/3.6
module load miket/vcflib/20140715
module load miket/CNVnator/0.3
module load miket/delly/0.5.5
# module load miket/bedtools/2.20.1
module load miket/bedtools/2.22.1
#module load miket/miniconda/3.5.5
module load miket/anaconda/2.0.1
# module load miket/anaconda3/2.0.1
module load miket/ctags/5.8
module load miket/ack/2.12
module load miket/fastqc/0.11.2
module load miket/trim_galore/0.3.7
module load miket/fastx/0.0.13
module load miket/samtools/1.0
module load miket/aspera-connect/3.4.2
module load miket/simNGS/1.7
module load miket/SVsim/0.1.1
module load miket/tmux/1.9a


# [[ -s "$HOME/.pythonbrew/etc/bashrc" ]] && source "$HOME/.pythonbrew/etc/bashrc"

PYTHONPATH=$PYTHONPATH:$HOME/code
PYTHONPATH=$PYTHONPATH:$HOME/code/dna-scripts
export PYTHONPATH

export LSF_INCLUDEDIR=/hptc_cluster/lsf/8.0/include
