# .bashrc

# User specific aliases and functions

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Load modules
if [ -f ~/.modulerc ]; then
    . ~/.modulerc
fi

# set -o vi

#PS1="\e[0;34m$PS1\e[m"

PYTHONPATH=$PYTHONPATH:$HOME/code
PYTHONPATH=$PYTHONPATH:$HOME/code/dna-scripts
PYTHONPATH=$PYTHONPATH:$HOME/code/svtoolkit
export PYTHONPATH

export LSF_INCLUDEDIR=/hptc_cluster/lsf/8.0/include

# Load last tmux session
# if [ $(hostname -s) == "eris1n3" ]; then
    # (tmux ls | grep -vq attached && tmux at) || tmux new
# fi

