# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# Base16 shell
# BASE16_SHELL="$HOME/.config/base16-shell/base16-twilight.dark.sh"
# BASE16_SHELL="$HOME/.config/base16-shell/base16-tomorrow.dark.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# Only display updated login message
cmp -s $HOME/.hushlogin /etc/motd
if [ $? != 0 ]; then
  tee $HOME/.hushlogin < /etc/motd
fi

# Don't want nano to be default editor
export VISUAL=vim
export EDITOR="$VISUAL"

# export TMPDIR=/scratch/miket/my520/tmp

# Set default reference
export GRCH37=/data/talkowski/tools/ref/Ensembl_hgGRCh37_71_reord_bwa07/Ensembl_hgGRCh37_71_ERCC_reord.fa

# User specific environment and startup programs

# Add github repositories to $PATH
PATH=$PATH:$HOME/code/classifier
PATH=$PATH:$HOME/code/bamstat
PATH=$PATH:$HOME/code/dna-scripts
PATH=$PATH:$HOME/code/dna-processing
PATH=$PATH:$HOME/code/sv-callers
PATH=$PATH:$HOME/code/talkowskidb
PATH=$PATH:$HOME/code/pycluster
PATH=$PATH:$HOME/code/readpaircluster

# For add_module.py
PATH=$PATH:/apps/modulefiles/lab/miket

# required for SMUFIN
PATH=$PATH:/apps/source/openmpi-1.6.3/bin

export PATH

# PYTHONPATH=$PYTHONPATH:$HOME/code
# PYTHONPATH=$PYTHONPATH:/data/talkowski/tools/local/lib/python
# PYTHONPATH=$PYTHONPATH:/data/talkowski/tools/local/lib/python3.2
# export PYTHONPATH

PERL5LIB=$PERL5LIB:/source/vcftools_0.1.9/vcftools_0.1.9/perl
export PERL5LIB

export DRMAA_LIBRARY_PATH=/data/talkowski/tools/local/lib/libdrmaa.so.1.0.3

# TODO: Handle in modules
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/apps/lab/miket/libevent/2.0.21/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/apps/lab/miket/meerkat/0.185/src/mybamtools/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/apps/source/openmpi-1.6.3/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/apps/source/zlib/1.2.8/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/apps/lab/miket/hdf/1.8.14/lib
export LD_LIBRARY_PATH

export HDF5INCLUDEDIR=/apps/lab/miket/hdf/1.8.14/include
export HDF5LIBDIR=/apps/lab/miket/hdf/1.8.14/lib

unset R_HOME
