# .bash_aliases
source ~/dotfiles/bash_aliases

# Shortcuts
alias l='ls -lh --group-directories-first'
alias nohead='sed -e "/^#/d"'
alias nb='jupyter notebook'
alias fvim='vim $(fzf --height 40% --reverse)'
alias wiki='cd ~/vimwiki; vim $(fzf --height 40% --reverse); cd -'

# Default options
