# .bash_aliases

# Shortcut for ls
alias l='ls -lh --group-directories-first'

# Automate cluster login
function erisone() {
    ping -c 1 erisone.partners.org &> /dev/null
    if [ $? -eq 0 ]; then
        ssh -tY my520@erisone.partners.org
    else
# Test tmux here
        ssh -tY my520@ssh.research.partners.org "ssh -tY my520@erisone.partners.org"
    fi
}

export -f erisone

alias tunnel='ssh my520@ssh.research.partners.org'
alias anthill='ssh msto@anthill.cs.dartmouth.edu'
