# .bashrc

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Command prompt
export PS1="[\u@\h \W]\$ "

# PATH
PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
export PATH

# MANPATH
MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH
export MANPATH

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

export VISUAL=vim
