# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

export CLICOLOR=1
eval `dircolors ~/.dir_colors`
export TERM=xterm-256color

# added by Miniconda3 3.18.3 installer
export PATH="/usr/local/bin/miniconda3/bin:$PATH"
